//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cafeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cafeler()
        {
            this.Menuler = new HashSet<Menuler>();
            this.Saatler = new HashSet<Saatler>();
            this.SosyalMedyalar = new HashSet<SosyalMedyalar>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Slogan { get; set; }
        public string Hakkinda { get; set; }
        public string Adres { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Telefon { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menuler> Menuler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saatler> Saatler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SosyalMedyalar> SosyalMedyalar { get; set; }
    }
}
