//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QRMenuEntities1 : DbContext
    {
        public QRMenuEntities1()
            : base("name=QRMenuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
        public virtual DbSet<TBLDUKKAN> TBLDUKKAN { get; set; }
        public virtual DbSet<TBLKAMPANYALAR> TBLKAMPANYALAR { get; set; }
        public virtual DbSet<TBLKATEGORILER> TBLKATEGORILER { get; set; }
        public virtual DbSet<TBLKULLANICILAR> TBLKULLANICILAR { get; set; }
        public virtual DbSet<TBLMASA> TBLMASA { get; set; }
        public virtual DbSet<TBLSAATLER> TBLSAATLER { get; set; }
        public virtual DbSet<TBLSIPARISLER> TBLSIPARISLER { get; set; }
        public virtual DbSet<TBLSOCIALMEDIA> TBLSOCIALMEDIA { get; set; }
        public virtual DbSet<TBLURUNLER> TBLURUNLER { get; set; }
    }
}
