//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDUKKAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLDUKKAN()
        {
            this.TBLKULLANICILAR1 = new HashSet<TBLKULLANICILAR>();
            this.TBLSAATLER = new HashSet<TBLSAATLER>();
        }
    
        public int DUKKANID { get; set; }
        public string DUKKANAD { get; set; }
        public string DUKKANSLOGAN { get; set; }
        public string DUKKANHAKKINDA { get; set; }
        public Nullable<int> DUKKANSAHIBI { get; set; }
        public string DUKKANADRES { get; set; }
        public Nullable<int> DUKKANSAAT { get; set; }
    
        public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKULLANICILAR> TBLKULLANICILAR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSAATLER> TBLSAATLER { get; set; }
    }
}
