//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICILAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKULLANICILAR()
        {
            this.TBLDUKKAN = new HashSet<TBLDUKKAN>();
        }
    
        public int KULLANICIID { get; set; }
        public string KULLANICIAD { get; set; }
        public string KULLANICISOYAD { get; set; }
        public string KULLANICIMAIL { get; set; }
        public string KULLANICIDOGUMGUNU { get; set; }
        public string KULLANICIRESIM { get; set; }
        public string KULLANICISIFRE { get; set; }
        public Nullable<int> KULLANICIDUKKAN { get; set; }
        public Nullable<byte> KULLANICIDURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDUKKAN> TBLDUKKAN { get; set; }
        public virtual TBLDUKKAN TBLDUKKAN1 { get; set; }
    }
}
