//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKAMPANYALAR
    {
        public int KAMPANYAID { get; set; }
        public string KAMPANYAACIKLAMA { get; set; }
        public Nullable<int> KAMPANYALIURUN { get; set; }
        public string KAMPANYASURESI { get; set; }
    
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
