//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSAATLER
    {
        public int CALISMASAATID { get; set; }
        public string PAZARTESI { get; set; }
        public string SALI { get; set; }
        public string CARSAMBA { get; set; }
        public string PERSEMBE { get; set; }
        public string CUMA { get; set; }
        public string CUMARTESI { get; set; }
        public string PAZAR { get; set; }
        public Nullable<int> DUKKANSAAT { get; set; }
    
        public virtual TBLDUKKAN TBLDUKKAN { get; set; }
    }
}
