//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSIPARISLER
    {
        public int SIPARISID { get; set; }
        public Nullable<int> MASANUMARASI { get; set; }
        public Nullable<int> SIPARISLER { get; set; }
        public Nullable<System.TimeSpan> GECENSURE { get; set; }
        public Nullable<decimal> TOPLAMFIYAT { get; set; }
        public Nullable<byte> SIPARISDURUM { get; set; }
    
        public virtual TBLMASA TBLMASA { get; set; }
    }
}
