//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUNLER()
        {
            this.TBLKAMPANYALAR = new HashSet<TBLKAMPANYALAR>();
        }
    
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public string URUNACIKLAMA { get; set; }
        public Nullable<decimal> URUNFIYAT { get; set; }
        public string URUNRESIM { get; set; }
        public Nullable<int> URUNKATEGORI { get; set; }
        public Nullable<byte> URUNDURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKAMPANYALAR> TBLKAMPANYALAR { get; set; }
        public virtual TBLKATEGORILER TBLKATEGORILER { get; set; }
    }
}
