//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public decimal Fiyat { get; set; }
        public string Resim { get; set; }
        public int KategoriID { get; set; }
        public Nullable<int> KampanyaID { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Kampanyalar Kampanyalar { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
